apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ruh-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/ruh-backend/ruh-api:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        env:
        - name: ANTHROPIC_API_KEY
          value: ***REMOVED***
        - name: API_HOST
          value: 0.0.0.0
        - name: API_PORT
          value: '8080'
        - name: DEBUG
          value: 'false'
        - name: ALLOWED_ORIGINS
          value: '*'
        - name: LOG_LEVEL
          value: INFO
  traffic:
  - percent: 100
    latestRevision: true
